paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  paintings:
    path: _paintings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  prints:
    path: _prints
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  news/posts:
    path: news/_posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  imagecdn:
    staging: https://ed-clarebassett-dev.imgix.net
    production: https://ed-clarebassett.imgix.net
  social:
    - name: Twitter
      icon: twitter
      username:
      url:
      desc: Follow us on Twitter
      share: true
    - name: Facebook
      icon: facebook
      username:
      url:
      desc: Like us on Facebook
      share: true
    - name: GitHub
      icon: github
      username:
      url:
      desc: Fork us on GitHub
      share: false
    - name: LinkedIn
      icon: linkedin
      username:
      url:
      desc: Connect with us on LinkedIn
      share: true
    - name: YouTube
      icon: youtube
      username:
      url:
      desc: Subscribe on YouTube
      share: false
    - name: Instagram
      icon: instagram
      username:
      url:
      desc: Follow me on Instagram
      share: false
    - name: Pinterest
      icon: pinterest
      username:
      url:
      desc: Follow me on Pinterest
      share: true
    - name: SoundCloud
      icon: soundcloud
      username:
      url:
      desc: Follow me on SoundCloud
      share: false
    - name: Vimeo
      icon: vimeo-square
      username:
      url:
      desc: Follow me on Vimeo
      share: false
  protocols:
    fb_image: /siteicon.png
    fb_image_width: 480
    fb_image_height: 480
    fb_image_type: image/png
    twitter_image: /siteicon.png
data_config: {}
timezone: Europe/London
